kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dkotlin.daemon.jvm.options="-Xmx1536m" -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true

# Automatically kill idle Gradle daemons faster (e.g., 30 minutes instead of 3 hours)
org.gradle.daemon.idletimeout=1800000