[versions]
agp = "7.2.1"

kotlin = "1.7.10"
kotlin_coroutines = "1.6.4"
kotlin_serialization = "1.3.3"
kotlin_datetime = "0.4.0"
compose_other = "1.2.0"
compose_activity = "1.5.1"
compose_compiler = "1.3.0-rc01"
accompanist = "0.25.0"
voyager = "1.0.0-rc02"
room = "2.4.3"
androidx_datastore = "1.0.0"
paging_runtime = "3.1.1"
paging_compose = "1.0.0-alpha15"
coil = "2.1.0"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlinCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin_coroutines" }
kotlinSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin_serialization" }
kotlinDateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin_datetime" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

androidX_dataStore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx_datastore" }

compose_compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose_compiler" }
compose_foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose_other" }
compose_ui = { module = "androidx.compose.ui:ui", version.ref = "compose_other" }
compose_material = { module = "androidx.compose.material:material", version.ref = "compose_other" }
compose_animation = { module = "androidx.compose.animation:animation", version.ref = "compose_other" }
compose_tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose_other" }
compose_toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose_other" }
compose_activity = { module = "androidx.activity:activity-compose", version.ref = "compose_activity" }

voyager_navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager_transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }

accompanist_systemUi = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist_pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist_swipeRefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }

room_runtime = { module = "androidx.room:room-ktx", version.ref = "room" }
room_compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room_paging = { module = "androidx.room:room-paging", version.ref = "room" }
room_test = { module = "androidx.room:room-testing", version.ref = "room" }

paging_runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging_runtime" }
paging_compose = { module = "androidx.paging:paging-compose", version.ref = "paging_compose" }

coil_base = { module = "io.coil-kt:coil-compose-base", version.ref = "coil" }
coil_gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil_video = { module = "io.coil-kt:coil-video", version.ref = "coil" }
