[versions]
agp = "7.3.1"
kotlin = "1.7.21"
kotlin_coroutines = "1.6.4"
kotlin_serialization = "1.4.1"
kotlin_datetime = "0.4.0"
compose_other = "1.3.1"
compose_activity = "1.6.1"
compose_compiler = "1.4.0-alpha02"
compose_material3 = "1.0.1"
accompanist = "0.28.0"
voyager = "1.0.0-rc03"
androidx_room = "2.4.3"
androidx_media = "1.0.0-beta03"
androidx_datastore = "1.0.0"
paging_runtime = "3.1.1"
paging_compose = "1.0.0-alpha17"
coil = "2.2.2"
dagger = "2.44.2"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlinCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin_coroutines" }
kotlinSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin_serialization" }
kotlinDateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin_datetime" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

androidX_dataStore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx_datastore" }

compose_compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose_compiler" }
compose_foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose_other" }
compose_ui = { module = "androidx.compose.ui:ui", version.ref = "compose_other" }
compose_material = { module = "androidx.compose.material:material", version.ref = "compose_other" }
compose_material3 = { module = "androidx.compose.material3:material3", version.ref = "compose_material3" }
compose_animation = { module = "androidx.compose.animation:animation", version.ref = "compose_other" }
compose_tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose_other" }
compose_toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose_other" }
compose_activity = { module = "androidx.activity:activity-compose", version.ref = "compose_activity" }

voyager_navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager_transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }

accompanist_systemUi = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist_pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist_swipeRefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }

room_runtime = { module = "androidx.room:room-ktx", version.ref = "androidx_room" }
room_compiler = { module = "androidx.room:room-compiler", version.ref = "androidx_room" }
room_paging = { module = "androidx.room:room-paging", version.ref = "androidx_room" }
room_test = { module = "androidx.room:room-testing", version.ref = "androidx_room" }

media_exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx_media" }
media_ui = { module = "androidx.media3:media3-ui", version.ref = "androidx_media" }
media_okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "androidx_media" }

paging_runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging_runtime" }
paging_compose = { module = "androidx.paging:paging-compose", version.ref = "paging_compose" }

coil_base = { module = "io.coil-kt:coil-compose-base", version.ref = "coil" }
coil_gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil_video = { module = "io.coil-kt:coil-video", version.ref = "coil" }

dagger_android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger_compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
dagger_hilt_plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
dagger_hilt_compiler = "androidx.hilt:hilt-compiler:1.0.0"
dagger_hilt_work = "androidx.hilt:hilt-work:1.0.0"

